# Generated by Django 6.0.7 on 2026-08-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['procedure_step__step_number'], 'permissions': [('assign_task', 'Can assign task')]},
        ),
    ]
