# Generated by Django 6.0.7 on 2026-09-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureexecution',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
