# Generated by Django 6.0.7 on 2026-09-07 12:46

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedures', '0013_rename_document_procedurestep_documents'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeBaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('chunk_number', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to='procedures.document')),
            ],
            options={
                'ordering': ['document_id', 'chunk_number'],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_number'), name='unique_chunk_per_document')],
            },
        ),
    ]
