# Generated by Django 6.0.7 on 2026-09-09 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('procedures', '0013_rename_document_procedurestep_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('document', 'Document'), ('procedure', 'Procedure')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_source', to='procedures.document')),
                ('procedure_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_source', to='procedures.procedureversion')),
            ],
        ),
        migrations.AddField(
            model_name='knowledgebaseitem',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai.knowledgesource'),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', False), ('procedure_version__isnull', True), ('source_type', 'document')), models.Q(('document__isnull', True), ('procedure_version__isnull', False), ('source_type', 'procedure')), _connector='OR'), name='knowledge_source_matches_type'),
        ),
    ]
