# Generated by Django 6.0.7 on 2026-09-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_migrate_documents_to_knowledge_sources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebaseitem',
            options={'ordering': ['source_id', 'chunk_number']},
        ),
        migrations.RemoveConstraint(
            model_name='knowledgebaseitem',
            name='unique_chunk_per_document',
        ),
        migrations.AddConstraint(
            model_name='knowledgebaseitem',
            constraint=models.UniqueConstraint(fields=('source', 'chunk_number'), name='unique_chunk_per_source'),
        ),
        migrations.RemoveField(
            model_name='knowledgebaseitem',
            name='document',
        ),
    ]
