# Generated by Django 6.0.7 on 2026-09-09 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_alter_knowledgebaseitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebaseitem',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai.knowledgesource'),
        ),
    ]
