# Generated by Django 6.0.7 on 2026-09-15 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_alter_knowledgebaseitem_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('procedure', 'Procedure'), ('procedure_step', 'Procedure step'), ('step_role', 'Step role'), ('documents', 'Documents')], max_length=20)),
                ('input_data', models.JSONField()),
                ('ai_output', models.JSONField()),
                ('final_output', models.JSONField(blank=True, null=True)),
                ('feedback_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('modified', 'Modified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
