# Generated by Django 6.0.7 on 2026-09-15 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_airecommendation'),
        ('procedures', '0013_rename_document_procedurestep_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airecommendation',
            old_name='reviewed_at',
            new_name='evaluated_at',
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='feedback_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='procedure_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to='procedures.procedureversion'),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='feedback_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('modified', 'Modified'), ('rejected', 'Rejected'), ('abandoned', 'Abandoned')], default='pending', max_length=20),
        ),
    ]
