# Generated by Django 6.0.7 on 2026-09-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_rename_reviewed_at_airecommendation_evaluated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airecommendation',
            name='feedback_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('modified', 'Modified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
