# Generated by Django 6.0.7 on 2026-09-16 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_alter_airecommendation_feedback_status'),
        ('procedures', '0013_rename_document_procedurestep_documents'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='knowledgesource',
            name='knowledge_source_matches_type',
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='ai_recommendation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_source', to='ai.airecommendation'),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='source_type',
            field=models.CharField(choices=[('document', 'Document'), ('procedure', 'Procedure'), ('ai_feedback', 'AI Feedback')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='knowledgesource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ai_recommendation__isnull', True), ('document__isnull', False), ('procedure_version__isnull', True), ('source_type', 'document')), models.Q(('ai_recommendation__isnull', True), ('document__isnull', True), ('procedure_version__isnull', False), ('source_type', 'procedure')), models.Q(('ai_recommendation__isnull', False), ('document__isnull', True), ('procedure_version__isnull', True), ('source_type', 'ai_feedback')), _connector='OR'), name='knowledge_source_matches_type'),
        ),
    ]
