# Generated by Django 6.0.7 on 2026-07-31 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0003_procedureversion_procedurestep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'permissions': [('approve_procedure', 'Can approve procedure'), ('generate_procedure_with_ai', 'Can generate procedure with AI')]},
        ),
    ]
