# Generated by Django 6.0.7 on 2026-08-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0004_alter_procedure_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
    ]
