# Generated by Django 6.0.7 on 2026-08-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0005_procedure_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedureversion',
            options={'ordering': ['-version_number']},
        ),
        migrations.AlterField(
            model_name='procedure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='procedureversion',
            constraint=models.UniqueConstraint(fields=('procedure', 'version_number'), name='unique_version_number_per_procedure'),
        ),
        migrations.AddConstraint(
            model_name='procedureversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('procedure',), name='unique_current_version_per_procedure'),
        ),
    ]
