# Generated by Django 6.0.7 on 2026-08-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0006_alter_procedureversion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('clarification_needed', 'Clarification Needed')], default='created', max_length=20),
        ),
    ]
