# Generated by Django 6.0.7 on 2026-08-11 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0007_alter_procedure_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procedureversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_proc_version', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedureversion',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='procedureversion',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
