# Generated by Django 6.0.7 on 2026-08-12 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0010_alter_procedureversion_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedureversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='procedureversion',
            name='unique_version_number_per_procedure',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='description',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='status',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='title',
        ),
        migrations.AddField(
            model_name='procedureversion',
            name='change_type',
            field=models.CharField(blank=True, choices=[('minor', 'Minor change'), ('major', 'Major change')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='procedureversion',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='procedureversion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedureversion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_procedure_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedureversion',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Draft'), ('created', 'Waiting for Approval'), ('completed', 'Approved'), ('rejected', 'Rejected'), ('clarification_needed', 'Clarification Needed')], default='in_progress', max_length=30),
        ),
        migrations.AddField(
            model_name='procedureversion',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedureversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='procedureversion',
            name='version_major',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedureversion',
            name='version_minor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedureversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_procedure_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procedureversion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='procedureversion',
            constraint=models.UniqueConstraint(condition=models.Q(('version_major__isnull', False), ('version_minor__isnull', False)), fields=('procedure', 'version_major', 'version_minor'), name='unique_version_number_per_procedure'),
        ),
        migrations.AddConstraint(
            model_name='procedureversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['in_progress', 'created', 'clarification_needed'])), fields=('procedure',), name='unique_active_revision_per_procedure'),
        ),
        migrations.RemoveField(
            model_name='procedureversion',
            name='version_number',
        ),
    ]
