# Generated by Django 6.0.7 on 2026-08-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0012_document_procedurestep_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedurestep',
            old_name='document',
            new_name='documents',
        ),
    ]
